<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Login' => 'Вход',
    'Please fill out the following fields to login:' => 'Пожалуйста, заполните следующие поля для входа:',
    'Forgot your password?' => 'Забыли пароль?',
    'Email' => 'Email',
    'Password' => 'Пароль',
    'Remember Me' => 'Запомнить меня',
    'Recover Password' => 'Восстановление Пароля',
    'Please fill out your email. A link to reset password will be sent there.' => 'Пожалуйста, введите адрес вашей электронной почты. Ссылка для сброса пароля будет выслана на него.',
    'Send' => 'Отправить',
    'User with this email is not found.' => 'Такой пользователь не найден',
    'Your account has been deactivated, please contact support for details.' => 'Ваш аккаунт был заблокирован, обратитесь в службу поддержки.',
    'Password reset for {0}' => 'Восстановление пароля для {0}',
    'Check your email for further instructions.' => 'Проверьте свою электронную почту для получения дальнейших инструкций.',
    'Sorry, we are unable to reset password for email provided.' => 'К сожалению, мы не можем сбросить пароль для этой электронной почты.',
    'Incorrect username or password.' => 'Неверное имя пользователя или пароль.',
    'User ID' => 'ID Пользователя',
    'Reset password' => 'Сброс пароля',
    'Please choose your new password:' => 'Пожалуйста, введите ваш новый пароль:',
    'Save' => 'Сохранить',
    'Signup' => 'Регистрация',
    'Please fill out the following fields to signup:' => 'Пожалуйста, заполните следующие поля для регистрации:',
    'Username' => 'Имя пользователя',
    'New password was saved.' => 'Новый пароль успешно сохранен.'
];