<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this user?' => 'Вы уверены, что хотите удалить этого пользователя?',
    'Email' => 'Email',
    'Error occurred while changing password.' => 'Произошла ошибка при смене пароля.',
    'Error occurred while deleting user.' => 'Произошла ошибка при удалении пользователя.',
    'Forgot your password?' => 'Забыли пароль?',
    'Incorrect email or password.' => 'Неправильный email или пароль.',
    'Last login' => 'Дата последнего входа',
    'Login' => 'Вход',
    'Password' => 'Пароль',
    'Password has been changed.' => 'Пароль был изменен.',
    'Password reset for {0}' => 'Восстановление пароля для {0}',
    'Please choose your new password:' => 'Пожалуйста, введите ваш новый пароль:',
    'Please fill out the following fields to login:' => 'Пожалуйста, заполните следующие поля для входа:',
    'Please fill out the following fields to signup:' => 'Пожалуйста, заполните следующие поля для регистрации:',
    'Please fill out your email. A link to reset password will be sent there.' => 'Пожалуйста, введите адрес вашей электронной почты. Ссылка для сброса пароля будет выслана на него.',
    'Please fix the following errors:' => 'Пожалуйста, исправьте следующие ошибки:',
    'Recover Password' => 'Восстановление Пароля',
    'Registration time' => 'Время регистрации',
    'Remember Me' => 'Запомнить меня',
    'Reset password' => 'Сброс пароля',
    'Save' => 'Сохранить',
    'Send' => 'Отправить',
    'Signup' => 'Регистрация',
    'Status' => 'Статус',
    'The role "{roleName}" is not found.' => 'Роль "{roleName}" не найдена.',
    'The role has been successfully assigned to the user.' => 'Роль успешно назначена пользователю.',
    'The role has been successfully revoked from the user.' => 'Роль успешно удалена у пользователя.',
    'This email address has already been taken.' => 'Этот адрес электронной почты уже занят.',
    'This role already assigned to this user.' => 'Эта роль уже назначена пользователю.',
    'This role is not assigned to this user.' => 'Эта роль не назначена пользователю.',
    'This username has already been taken.' => 'Это имя пользователя уже занято.',
    'User has been created.' => 'Пользователь был создан.',
    'User has been deleted.' => 'Пользователь был удален.',
    'User is not found.' => 'Пользователь не найден.',
    'User with this email is not found.' => 'Такой пользователь не найден.',
    'Username' => 'Имя пользователя',
    'Your account has been deactivated, please contact support for details.' => 'Ваш аккаунт был заблокирован, обратитесь в службу поддержки.',
];
