<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this user?' => 'Ви дійсно хочете видалити цього користувача?',
    'Email' => 'Email',
    'Error occurred while changing password.' => 'При зміні пароля виникла помилка.',
    'Error occurred while deleting user.' => 'Виникла помилка при видаленні користувача.',
    'Forgot your password?' => 'Забули пароль?',
    'Incorrect email or password.' => 'Неправильний email або пароль.',
    'Last login' => 'Останняя авторизація',
    'Login' => 'Вхід',
    'Password' => 'Пароль',
    'Password has been changed.' => 'Пароль було успішно змінено',
    'Password reset for {0}' => 'Відновлення пароля для {0}',
    'Please choose your new password:' => 'Будь ласка, введіть ваш новий пароль:',
    'Please fill out the following fields to login:' => 'Будь ласка, заповніть наступні поля для входу:',
    'Please fill out the following fields to signup:' => 'Будь ласка, заповніть наступні поля для реєстрації:',
    'Please fill out your email. A link to reset password will be sent there.' => 'Будь ласка, введіть адресу вашої електронної пошти. Посилання для скидання пароля буде вислана на нього.',
    'Please fix the following errors:' => 'Виправте наступні помилки:',
    'Recover Password' => 'Відновлення Пароля',
    'Registration time' => 'Час реєстрації',
    'Remember Me' => 'Запам\'ятати мене',
    'Reset password' => 'Скидання пароля',
    'Save' => 'Зберегти',
    'Send' => 'Відправити',
    'Signup' => 'Реєстрація',
    'Status' => 'Статус',
    'The role "{roleName}" is not found.' => 'Роль "{roleName}" не знайдено.',
    'The role has been successfully assigned to the user.' => 'Роль успішно призначено користувачу.',
    'The role has been successfully revoked from the user.' => 'Роль успішно видалена у користувача.',
    'This email address has already been taken.' => 'Цей адрес електронної пошти вже зайнятий.',
    'This role already assigned to this user.' => 'Ця роль вже призначена користувачеві.',
    'This role is not assigned to this user.' => 'Ця роль не призначена користувачеві.',
    'This username has already been taken.' => 'Це ім\'я вже зайняте .',
    'User has been created.' => 'Користувач був створений.',
    'User has been deleted.' => 'Користувач був видалений.',
    'User is not found.' => 'Користувач не знайдений.',
    'User with this email is not found.' => 'Такий користувач не знайдений',
    'Username' => 'Ім\'я користувача',
    'Your account has been deactivated, please contact support for details.' => 'Ваш аккаунт був заблокований, зверніться в службу підтримки.',
];
