<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Login' => 'Вхід',
    'Please fill out the following fields to login:' => 'Будь ласка, заповніть наступні поля для входу:',
    'Forgot your password?' => 'Забули пароль?',
    'Email' => 'Email',
    'Password' => 'Пароль',
    'Remember Me' => 'Запам\'ятати мене',
    'Recover Password' => 'Відновлення Пароля',
    'Please fill out your email. A link to reset password will be sent there.' => 'Будь ласка, введіть адресу вашої електронної пошти. Посилання для скидання пароля буде вислана на нього.',
    'Send' => 'Відправити',
    'User with this email is not found.' => 'Такий користувач не знайдений',
    'Your account has been deactivated, please contact support for details.' => 'Ваш аккаунт був заблокований, зверніться в службу підтримки.',
    'Password reset for {0}' => 'Відновлення пароля для {0}',
    'Check your email for further instructions.' => 'Перевірте свою електронну пошту для отримання подальших інструкцій.',
    'Sorry, we are unable to reset password for email provided.' => 'На жаль, ми не можемо скинути пароль для електронної пошти.',
    'Incorrect username or password.' => 'Невірне ім\'я користувача або пароль.',
    'User ID' => 'ID Користувача',
    'Reset password' => 'Скидання пароля',
    'Please choose your new password:' => 'Будь ласка, введіть ваш новий пароль:',
    'Save' => 'Зберегти',
    'Signup' => 'Реєстрація',
    'Please fill out the following fields to signup:' => 'Будь ласка, заповніть наступні поля для реєстрації:',
    'Username' => 'Ім\'я користувача',
    'New password was saved.' => 'Новий пароль було успішно збережено.',
    'This email address has already been taken.' => 'Цей адрес електронної пошти вже зайнятий.',
    'This username has already been taken.' => 'Це ім\'я вже зайняте.',
    'Status' => 'Статус',
    'lastLogin' => 'Дата останнього входу',
];
