<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Login' => 'Login',
    'Please fill out the following fields to login:' => 'Please fill out the following fields to login:',
    'Forgot your password?' => 'Forgot your password?',
    'Email' => 'Email',
    'Password' => 'Password',
    'Remember Me' => 'Remember Me',
    'Recover Password' => 'Recover Password',
    'Please fill out your email. A link to reset password will be sent there.' => 'Please fill out your email. A link to reset password will be sent there.',
    'Send' => 'Send',
    'User with this email is not found.' => 'User with this email is not found.',
    'Your account has been deactivated, please contact support for details.' => 'Your account has been deactivated, please contact support for details.',
    'Password reset for {0}' => 'Password reset for {0}',
    'Check your email for further instructions.' => 'Check your email for further instructions.',
    'Sorry, we are unable to reset password for email provided.' => 'Sorry, we are unable to reset password for email provided.',
    'Incorrect username or password.' => 'Incorrect username or password.',
    'User ID' => 'User ID',
    'Reset password' => 'Reset password',
    'Please choose your new password:' => 'Please choose your new password:',
    'Save' => 'Save',
    'Signup' => 'Signup',
    'Please fill out the following fields to signup:' => 'Please fill out the following fields to signup:',
    'Username' => 'Username',
    'New password was saved.' => 'New password was saved.',
    'This email address has already been taken.' => 'This email address has already been taken.',
    'This username has already been taken.' => 'This username has already been taken.',
    'Status' => 'Status'
];